name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DEBUG: 1

jobs:
  debug-deploy:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - run:
      name: Activate venv and install dep
      command: |
        echo 'Bonjour, projet en mode prod'
        python -m venv venv
        . venv/bin/activate
        pip install -r requirements.txt
    - run:
      if: ${{ env.DEBUG == 1 }}
      name: Run tests
      command: |
        echo 'Bonjour, projet en mode prod'
        black --line-length=99 .
        flake8
        python manage.py test

  production-deploy:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - run:
      name: Activate venv and install dep
      command: |
        echo 'Bonjour, projet en mode prod'
        python -m venv venv
        . venv/bin/activate
        pip install -r requirements.txt
    - run:
      if: ${{ env.DEBUG == 0 }}
      name: Run tests
      command: |
        echo 'Bonjour, projet en mode prod'
        black --line-length=99 .
        flake8
        python manage.py test
