name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DEBUG: 1

jobs:

  pre-commit:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: flake8 --all-files

  build:
    runs-on: windows-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Activate venv and install dep (debug mod)
      if: ${{ env.DEBUG == 1 }}
      run: |
        echo 'Hi, project in DEV mod'
        python -m venv venv
        . venv/scripts/activate
        echo 'requirements setup...'
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    - name: install dep (prod mod)
      if: ${{ env.DEBUG == 0 }}
      run: |
        echo 'Hi, project in PROD mod'
        python -m pip install --upgrade pip
        echo 'requirements setup...'
        pip install -r requirements.txt
    - name: Black test
      run: |
        . venv/scripts/activate
        echo 'black running...'
        black --line-length=99 .
    - name: Linting test
      run: |
        . venv/scripts/activate
        echo 'flake8 running...'
        flake8
    - name: Other tests
      run: |
        . venv/scripts/activate
        echo 'tests running...'
        python manage.py test

  docker-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: projet-13-server:latest
      - name: Build docker image
        run: |
          echo "build docker image now..."
          docker build https://github.com/thomas-barbato/projet-13
